# Generated by Django 3.2.16 on 2023-01-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roon',
            new_name='Room',
        ),
    ]
