# Generated by Django 4.1.5 on 2023-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
